### ISSUE TITLE
 Task :conclave-grpc:compileKotlin FAILED

### ISSUE THREAD

**Issue by v13s** [R3Conclave/cordacon-conclave-tutorial#1]
Build failed while trying to setup the project over Ubuntu 18.04.

Java Version:
openjdk version "1.8.0_282"
OpenJDK Runtime Environment (build 1.8.0_282-8u282-b08-0ubuntu1~18.04-b08)
OpenJDK 64-Bit Server VM (build 25.282-b08, mixed mode)

Kotlin version 1.4.30-release-302 (JRE 1.8.0_282-8u282-b08-0ubuntu1~18.04-b08)
(failed with 1.4.10 as well)

Following error was received:

root@cloudvm:/opt/cordacon-conclave-tutorial# gradle host:shadowJar

> Task :conclave-grpc:compileKotlin
e: /opt/cordacon-conclave-tutorial/conclave-grpc/src/main/kotlin/com/r3/conclave/grpc/ConclaveGRPCMethods.kt: (28, 54): Unresolved reference: readAllBytes
e: /opt/cordacon-conclave-tutorial/conclave-grpc/src/main/kotlin/com/r3/conclave/grpc/ConclaveGRPCMethods.kt: (33, 86): Unresolved reference: readAllBytes
e: /opt/cordacon-conclave-tutorial/conclave-grpc/src/main/kotlin/com/r3/conclave/grpc/ConclaveGRPCMethods.kt: (37, 65): Unresolved reference: nullInputStream

> Task :conclave-grpc:compileKotlin FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':conclave-grpc:compileKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 24s
1 actionable task: 1 executed
root@ticketing:/opt/cordacon-con

Any help appreciated.

**Comment by shamsasari** [comment]
Can you try with the Gradle wrapper: `./gradlew host:shadowJar`

**Comment by v13s** [comment]
Yes. I get the same error when I try the ./gradlew host:shadowJar as well.

**Comment by v13s** [comment]
Fixed after switching to openjdk-11 instead of openjdk-8.

**Comment by shamsasari** [comment]
I'm glad you got that working. Odd that it didn't work in Java 8 for you.
